# Site
name: 'BEF-China'
description: 'Biodiversity and Ecosystem Functioning Experiment in Subtropical Forest in China'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'befchina@163.com'
# mailchimp-list:

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
# - jekyll-feed

authors:
    sal:
      name:           Sal
      site:           https://www.example.com
      avatar:         /assets/avatar/avatar1.jpg
      bio:            "Hi, I am Sal, a PhD student working in BEF-China. Currently I'm working on ..."
      email:          example@gmail.com
      twitter:        https://twitter.com

    jane:
      name:           Jane
      site:           https://www.example.com
      avatar:         /assets/avatar/jane.jpg
      bio:            "Blogger, love to explore new ideas and write!"
      email:          example@gmail.com
      twitter:        https://twitter.com

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10
paginate_path: "/news/page:num/"

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
